### ISSUE TITLE
开团.js有点问题，似乎遗漏了定义变量

### ISSUE THREAD

**Issue by liuzj288** [XiTianGame/Yunzai#1]
![image](https://user-images.githubusercontent.com/13833404/212787094-57b407b1-0736-49d7-88f6-86265e162c3f.png)

**Comment by XiTianGame** [comment]
机器人的回复已经提示了，本地resource/kunkun文件夹内没有图，如果需要使用本地图库，你需要在网上找一些小黑子整理好的图包放入此文件夹。如果不想使用本地，可以在插件第十行中将mode改为0，调用网络接口发图，但是会慢一点，所以默认是使用本地

**Comment by liuzj288** [comment]
> 

已经放了图了还是这个提示
